apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    component: {{ .Chart.Name }}
spec:
  replicas: {{ pluck .Values.global.env .Values.replicas.market_radar_management_front | first | default .Values.replicas.market_radar_management_front._default }}
  selector:
    matchLabels:
      component: {{ .Chart.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        component: {{ .Chart.Name }}
    spec:
      containers:
      - name: market-radar-management-front
{{ tuple "market-radar-management-front" . | include "dapp_container_image" | indent 8 }}
        workingDir: "/var/www/html/"
        command: ["nginx", "-g", "daemon off;"]
        ports:
        - containerPort: {{ pluck .Values.global.env .Values.app.market_radar_management_front.rest_port | first | default .Values.app.market_radar_management_front.rest_port._default }}
          name: http
          protocol: TCP
        env:
{{ tuple "market-radar-management-front" . | include "dapp_container_env" | indent 8 }}
{{- include "market_radar_management_front_envs" . | indent 8 }}
{{- include "market_radar_management_front_resources" . | indent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  clusterIP: None
  selector:
    component: {{ .Chart.Name }}
  ports:
  - name: http
    port: {{ pluck .Values.global.env .Values.app.market_radar_management_front.rest_port | first | default .Values.app.market_radar_management_front.rest_port._default }}
